# Generated by Django 3.0 on 2020-10-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dir1', models.CharField(max_length=150)),
                ('dir2', models.CharField(max_length=150)),
                ('rfc', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
    ]
