# Generated by Django 3.1.2 on 2020-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_client_dir3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NOM')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='dir1',
            field=models.CharField(max_length=150, verbose_name='Dir 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dir2',
            field=models.CharField(max_length=150, verbose_name='Dir 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dir3',
            field=models.CharField(max_length=150, verbose_name='Dir 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(max_length=50, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='part',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='part',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='NOM'),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.CharField(max_length=100, verbose_name='No de Parte'),
        ),
    ]
