# Generated by Django 3.1.2 on 2020-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201011_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='NOM'),
        ),
    ]
