# Generated by Django 3.1.2 on 2020-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201011_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='country',
            field=models.CharField(default='Mexico', max_length=100, verbose_name='País'),
        ),
    ]
